spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现路由，自动识别 nacos 注册的服务
          lower-case-service-id: true
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1 # 去掉 /api


